name: Upload latest OpenWrt to cowtransfer

on:
  push:
    branches:
      - master
    paths:
      - '.github/workflows/action-test.yml'
 
jobs:
  build:
    runs-on: ubuntu-latest
    if: github.event.repository.owner.id == github.event.sender.id
    
    steps:
    - name: Checkout
      uses: actions/checkout@master

    - name: Initialization environment
      env:
        DEBIAN_FRONTEND: noninteractive
      run: |
        chmod +x cowtransfer-uploader
        tar -zcvf cow.tar.gz cowtransfer-uploader

    - name: Upload to cowtransfer
      run: |
        ./cowtransfer-uploader -p 2 cow.tar.gz
